### ISSUE TITLE
Swarm, Kubernetes

### ISSUE THREAD

**Issue by Yzrsah** [Springjunky/docker-local-build-environment#4]
Nice work on your project.
The most important thing for a local build environment is swarm support.
Cause I have a bunch of different computers. Sometimes I want to perform a heavy build on a small laptop.

**Comment by Springjunky** [comment]
This experimental setup is not designed for any k8s or swarm.
Docker swarm is dead afaik and in a k8s environment there is no need for docker-compose or nginx because of k8s pods and the  overlay network.
With a bunch of different computers to deploy I would prefer a vagrant setup and ansible ;-)
Perhaps minicube https://kubernetes.io/docs/setup/minikube/ could be an option for you

So what is your intention ?

**Comment by Zyrsha** [comment]
Intention:

1) I have >100 cores available.
2) These cores are usually idle.
3) These computers are running Windows, Linux, macOS.
4) I am typing on a laptop with 4 cores.
5) I want to build something in 5 minutes instead of 45 minutes.
6) I want to easily deploy a local build environment node to each of these computers.
7) I want a high level integration of cache and control of artifacts.
8) I want multiple users to be able to use the build environment.
9) I want the users who clone the project to be able to easily use this build environment on their own local setups.
10) I want the entire thing to be in a beautiful GitHub project integrating multiple parties together.
11) The build environment should support Docker, GitLab, GitLab-runner, Jenkins, and integrate with Ansible.
12) The build environment target should be able to easily switch between Local-CPU-only, Swarm, and remote Gitlab CI.
13) Vendors are limited to supporting their own projects, therefore Minikube does not have integrations with i.e. GitLab or Jenkins the way that a project like yours can.

**Comment by Zyrsha** [comment]
Intention:

1) I have >100 cores available.
2) These cores are usually idle.
3) These computers are running Windows, Linux, macOS.
4) I am typing on a laptop with 4 cores.
5) I want to build something in 5 minutes instead of 45 minutes.
6) I want to easily deploy a local build environment node to each of these computers.
7) I want a high level integration of cache and control of artifacts.
8) I want multiple users to be able to use the build environment.
9) I want the users who clone the project to be able to easily use this build environment on their own local setups.
10) I want the entire thing to be in a beautiful GitHub project integrating multiple parties together.
11) The build environment should support Docker, GitLab, GitLab-runner, Jenkins, and integrate with Ansible.
12) The build environment target should be able to easily switch between Local-CPU-only, Swarm, and remote Gitlab CI.
13) Vendors are limited to supporting their own projects, therefore Minikube does not have integrations with i.e. GitLab or Jenkins the way that a project like yours can.

**Comment by Zyrsha** [comment]
Intention:

1) I have >100 cores available.
2) These cores are usually idle.
3) These computers are running Windows, Linux, macOS.
4) I am typing on a laptop with 4 cores.
5) I want to build something in 5 minutes instead of 45 minutes.
6) I want to easily deploy a local build environment node to each of these computers.
7) I want a high level integration of cache and control of artifacts.
8) I want multiple users to be able to use the build environment.
9) I want the users who clone the project to be able to easily use this build environment for their own local setups.
10) I want the entire thing to be in a beautiful GitHub project integrating multiple parties together.
11) The build environment should support Docker, GitLab, GitLab-runner, Jenkins, and integrate with Ansible.
12) The build environment target should be able to easily switch between Local-CPU-only, Swarm, and remote Gitlab CI.
13) Vendors are limited to supporting their own projects in their own perceived self-interest, therefore Minikube does not have integrations with i.e. GitLab or Jenkins the way that a project like yours can.

**Comment by Zyrsha** [comment]
Intention:

1) I have >100 cores available.
2) These cores are usually idle.
3) These computers are running Windows, Linux, macOS.
4) I am typing on a laptop with 4 cores.
5) I want to build something in 5 minutes instead of 45 minutes.
6) I want to easily deploy a local build environment node to each of these computers.
7) I want a high level integration of cache and control of artifacts.
8) I want multiple users to be able to use the build environment.
9) I want the users who clone the project to be able to easily use this build environment for their own local setups.
10) I want the entire thing to be in a beautiful GitHub project integrating multiple parties together.
11) The build environment should support Docker, GitLab, GitLab-runner, Jenkins, and integrate with Ansible.
12) The build environment target should be able to easily switch between Local-CPU-only, Swarm, and remote Gitlab CI.
13) Vendors are limited to supporting their own projects, therefore Minikube does not have integrations with i.e. GitLab or Jenkins the way that a project like yours can.

**Comment by Yzrsah** [comment]
Intention:

1) I have >100 cores available.
2) These cores are usually idle.
3) These computers are running Windows, Linux, macOS.
4) I am typing on a laptop with 4 cores.
5) I want to build something in 5 minutes instead of 45 minutes.
6) I want to easily deploy a local build environment node to each of these computers.
7) I want a high level integration of cache and control of artifacts.
8) I want multiple users to be able to use the build environment.
9) I want the users who clone the project to be able to easily use the same build environment for their own local setups.
10) I want the entire thing to be in a beautiful GitHub project integrating multiple parties together.
11) The build environment should support Docker, GitLab, GitLab-runner, Jenkins, Kubernetes, and integrate with Ansible.
12) The build environment target should be able to easily switch between Local-CPU-only, Swarm, and remote Gitlab CI.
13) The build environment should be modular in order to support other CI targets besides Gitlab CI.
14) The GitHub project should be easy to contribute to, without being owned by a specific vendor.
15) Vendors are limited to supporting their own projects, therefore Minikube does not have integrations with i.e. GitLab or Jenkins the way that a project like yours can.

**Comment by Springjunky** [comment]
WOW ! Sorry my project is more or less only a playground, I have no acces to hundred of cores.
